
server:
  port: 8080

# mysql datasource and jpa (append to existing file)
spring:
  application:
    name: LOG
  datasource:
    url: jdbc:mysql://localhost:3306/logdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  ai:
    openai:

      api-key: mh


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  mail:
    ##host: smtp.office365.com add email config here
    host: smtp.gmail.com
    port: 587
    username: demo@gmail.com
    password: ayfc xobw zlyh uqcs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # File upload configuration (FIXED: moved to correct position)
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

alert:
  enabled: true  # Set to false to disable all alerts
  threshold: 10
  application:
    name: LOG-ANALYZER
    environment: DEVELOPMENT
    threshold: 10




springdoc:
  swagger-ui:
    path: /swagger-ui.html


# AI Properties
ai:
  api:
    base-url: https://api.groq.com/openai/v1

    key: mh

    model: allam-2-7b
    timeout-ms: 1
    endPoint: /chat/completions
    role: user
    temperature: 0.1
    stream: false
    timeout: 90
    token: 2000



