
server:
  port: 8080

# mysql datasource and jpa (append to existing file)
spring:
  application:
    name: LOG
  datasource:
    url: jdbc:mysql://localhost:3306/logdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  ai:
    openai:
      api-key: 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

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


springdoc:
  swagger-ui:
    path: /swagger-ui.html


# AI Properties
ai:
  api:
    base-url: https://api.groq.com/openai/v1
    key: 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
    model: allam-2-7b
    timeout-ms: 60000
    endPoint: /chat/completions
    role: user
    temperature: 0.1
    stream: false
    timeout: 90
    token: 2000



